/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-08-05 03:22:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import dto.Product;
import dao.ProductRepository;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1656558644000L));
    _jspx_dependants.put("jar:file:/D:/jspStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/WebMarket/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/jspStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/WebMarket/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dto.Product");
    _jspx_imports_classes.add("dao.ProductRepository");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script>\r\n");
      out.write("	function checkOrder(){\r\n");
      out.write("		");

		  ArrayList list = (ArrayList<Product>)session.getAttribute("cartList");

		  if(list == null || list.size() == 0){
		
      out.write("\r\n");
      out.write("			  alert(\"선택하신 상품내역이 없습니다!\");\r\n");
      out.write("			  location.href = './cart.jsp';\r\n");
      out.write("			  return false;\r\n");
      out.write("		");

		   }	
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("	$(\".qtyUp,.qtyDown\").click(function(){\r\n");
      out.write("    	\r\n");
      out.write("        var qtyUp = $(this);\r\n");
      out.write("        var tr = qtyUp.parent().parent();//tr\r\n");
      out.write("        var td = tr.children();//td\r\n");
      out.write("        var rowNum = tr.index()+1;//현재행\r\n");
      out.write("        var pid = td.eq(0).text().split('-')[0];//상품코드\r\n");
      out.write("        var price = Number(td.eq(1).text());//가격\r\n");
      out.write("        \r\n");
      out.write("        if($(this).hasClass('qtyUp')){\r\n");
      out.write("        	var qty = Number(td.children(\"input.qty\").val())+1;\r\n");
      out.write("        }else{\r\n");
      out.write("        	var qty = Number(td.children(\"input.qty\").val())-1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //1증가 된 수량을 수량칸에 대입\r\n");
      out.write("        $(this).parent().parent().children(\"td\").children(\"input.qty\").val(qty);\r\n");
      out.write("      \r\n");
      out.write("        document.cartQtyUpdate.pcode.value=pid;  \r\n");
      out.write("		document.cartQtyUpdate.qty.value=qty; \r\n");
      out.write("		\r\n");
      out.write("		document.cartQtyUpdate.submit();\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("     \r\n");
      out.write("});  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");

	//톰캣서버에서 부여하는 JSESSIONID 값
	//F12에서도 확인가능
	String cartId = session.getId();

      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>장바구니</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"jumbotron\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h1 class=\"display-3\">장바구니</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<table width=\"100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"left\"><a href=\"./deleteCart.jsp?cartId=");
      out.print(cartId);
      out.write("\" class=\"btn btn-danger\">삭제하기</a></td>\r\n");
      out.write("					<td align=\"right\">\r\n");
      out.write("					<a href=\"./shippingInfo.jsp?cartId=");
      out.print(cartId);
      out.write("\"\r\n");
      out.write("					   onclick=\"return checkOrder()\" \r\n");
      out.write("					   class=\"btn btn-success\">주문하기</a></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>	\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div style=\"padding-top:50px\">\r\n");
      out.write("			<table id=\"cart\" class=\"table table-hover\">\r\n");
      out.write("				<tbody id=\"test_tbody\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"text-center col-sm-4\">상품</th>\r\n");
      out.write("					<th class=\"text-center col-sm-2\">가격</th>\r\n");
      out.write("					<th class=\"text-center col-sm-2\">수량</th>\r\n");
      out.write("					<th class=\"text-right col-sm-2\">소계</th>\r\n");
      out.write("					<th class=\"text-center col-sm-2\">비고</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

					int sum = 0;
					ArrayList<Product> cartList = (ArrayList<Product>)session.getAttribute("cartList");
					
					if(cartList == null){
						cartList = new ArrayList<Product>();
					}
					
					//total : 소계를 계산
					//sum : 총계
					for(int i=0;i<cartList.size();i++){
						Product product = cartList.get(i);
						int total = product.getUnitPrice()*product.getQuantity();
						sum += total;
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<tr class=\"tr_this\">\r\n");
      out.write("					<td>");
      out.print(product.getProductId());
      out.write('-');
      out.print(product.getPname());
      out.write("</td>\r\n");
      out.write("					<td class=\"text-center col-sm-2\">");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
        // /cart.jsp(123,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f0.setValue(product.getUnitPrice());
        int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
        _jspx_th_fmt_005fformatNumber_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
      }
      out.write("</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input style=\"text-align:center\" readonly type=\"text\" size=\"2\" name=\"qty\" class=\"qty\" value=\"");
      out.print(product.getQuantity());
      out.write("\" />\r\n");
      out.write("					    &nbsp;&nbsp;\r\n");
      out.write("					    <i class=\"fa fa-arrow-circle-up fa-lg qtyUp\" style=\"color:blue\"></i>\r\n");
      out.write("					    &nbsp;&nbsp;\r\n");
      out.write("					    <i class=\"fa fa-arrow-circle-down fa-lg qtyDown\" style=\"color:red\"></i>\r\n");
      out.write("				\r\n");
      out.write("					</td>\r\n");
      out.write("					<td class=\"text-right col-sm-2 subamt\">");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
        // /cart.jsp(132,44) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f1.setValue(total);
        int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
        _jspx_th_fmt_005fformatNumber_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
      }
      out.write("</td>\r\n");
      out.write("					<td class=\"text-center col-sm-2\"><a href=\"./removeCart.jsp?id=");
      out.print(product.getProductId());
      out.write("\" class=\"badge badge-danger\">삭제</a></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					<th class=\"text-right\">총액</th>\r\n");
      out.write("					<th class=\"text-right sumamt\">");
      //  fmt:formatNumber
      org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
      boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
      try {
        _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
        // /cart.jsp(143,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatNumber_005f2.setValue(sum);
        int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
        if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
        _jspx_th_fmt_005fformatNumber_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
      }
      out.write("</th>\r\n");
      out.write("					<th></th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<a href=\"./products.jsp\" class=\"btn btn-warning\">&laquo;쇼핑 계속하기</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<form id=\"cartQtyUpdate\" name=\"cartQtyUpdate\" action=\"cartUpdate.jsp\" method=\"post\">\r\n");
      out.write("		<input type=\"hidden\" name=\"pcode\">\r\n");
      out.write("		<input type=\"hidden\" name=\"qty\">\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
